default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
development:
  <<: *default
  database: Trailer_Finder_development
  host: localhost
  user: development
  password: postgres
production:
  <<: *default
  database: Trailer_Finder_production
  username: deployed
  password: <%= ENV['POSTY_DATABASE_PASSWORD'] %>
