default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
development:
  <<: *default
  database: deployed_development
  host: localhost
  user: postgres
  password: postgres
production:
  <<: *default
  database: deployed_production
  username: deployed
  password: <%= ENV['POSTY_DATABASE_PASSWORD'] %>
